const { contextBridge, ipcRenderer } = require('electron');

const invoke = (ch, ...a) => ipcRenderer.invoke(ch, ...a);
const EVENTS = ['steam', 'accounts', 'account', 'switch', 'stats', 'link', 'zoom', 'update', 'launch', 'launch-end', 'display-changed', 'notice', 'tray-show'];

contextBridge.exposeInMainWorld('api', {
  state: () => invoke('state'),
  switchTo: sid => invoke('switch', sid),
  closeSteam: () => invoke('steam:close'),
  startSteam: () => invoke('steam:start'),
  addAccount: () => invoke('add'),
  cancelAdd: () => invoke('add:cancel'),
  forget: sid => invoke('forget', sid),
  setMeta: (sid, patch) => invoke('meta', sid, patch),
  setSettings: patch => invoke('settings', patch),
  browseSteam: () => invoke('steam:browse'),
  refreshStats: sid => invoke('stats:refresh', sid),
  linkQR: sid => invoke('link:qr', sid),
  linkPassword: (sid, login, pw, remember) => invoke('link:pw', sid, login, pw, remember),
  linkToken: (sid, token) => invoke('link:token', sid, token),
  linkCode: code => invoke('link:code', code),
  linkCancel: () => invoke('link:cancel'),
  unlink: sid => invoke('unlink', sid),
  clearCredentials: sid => invoke('credentials:clear', sid),
  openProfile: url => invoke('open', url),
  checkUpdates: () => invoke('update:check'),
  installUpdate: () => invoke('update:install'),
  vaultStatus: () => invoke('vault:status'),
  vaultUnlock: pw => invoke('vault:unlock', pw),
  vaultSet: (pw, autoUnlock) => invoke('vault:set', pw, autoUnlock),
  vaultChange: (oldPw, newPw) => invoke('vault:change', oldPw, newPw),
  vaultRemove: pw => invoke('vault:remove', pw),
  vaultAutoUnlock: on => invoke('vault:autounlock', on),
  libList: () => invoke('lib:list'),
  libSet: (id, patch) => invoke('lib:set', id, patch),
  openSteamPage: (kind, appid) => invoke('steam:page', kind, appid),
  libPickExe: () => invoke('lib:pickExe'),
  libPickImage: () => invoke('lib:pickImage'),
  libSaveCustom: game => invoke('lib:saveCustom', game),
  libRemoveCustom: id => invoke('lib:removeCustom', id),
  libRestoreCustom: saved => invoke('lib:restoreCustom', saved),
  play: id => invoke('game:play', id),
  stopGame: () => invoke('game:stop'),
  shortcut: id => invoke('game:shortcut', id),
  displays: () => invoke('display:list'),
  displayModes: id => invoke('display:modes', id),
  saveResProfile: p => invoke('res:save', p),
  removeResProfile: id => invoke('res:remove', id),
  testResProfile: id => invoke('res:test', id),
  testDisplay: id => invoke('display:test', id),
  restoreDisplay: () => invoke('display:restore'),
  applyNormalDisplay: () => invoke('display:normal'),
  audioDevices: () => invoke('audio:list'),
  libPickApp: () => invoke('lib:pickApp'),
  playLog: () => invoke('play:log'),
  exportBackup: () => invoke('backup:export'),
  importBackup: () => invoke('backup:import'),
  trayData: () => invoke('tray:data'),
  playSessions: () => invoke('play:sessions'),
  steamLaunchOpts: id => invoke('lib:steamOpts', id),
  cs2Info: sid => invoke('cs2:info', sid),
  cs2Autoexec: (sid, text) => invoke('cs2:autoexec', sid, text),
  cs2Copy: (fromSid, toSid) => invoke('cs2:copy', fromSid, toSid),
  traySize: h => ipcRenderer.send('tray:size', h),
  trayOpen: () => ipcRenderer.send('tray:open'),
  trayHide: () => ipcRenderer.send('tray:hide'),
  trayQuit: () => ipcRenderer.send('tray:quit'),
  win: action => ipcRenderer.send('win', action),
  on: (ch, fn) => {
    if (!EVENTS.includes(ch)) throw new Error('Unknown channel ' + ch);
    const h = (_, ...a) => fn(...a);
    ipcRenderer.on(ch, h);
    return () => ipcRenderer.removeListener(ch, h);
  },
});
